apiVersion: apps/v1 
kind: Deployment
metadata:
  name: regapp-deployment
  labels: 
     app: regapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: 559050235518.dkr.ecr.us-east-1.amazonaws.com/image-1232323:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
